### ISSUE TITLE
Invalid object exceptions

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/almond-cloud#103]
From time to time, the following is logged in Travis:
```
Error: Invalid object 0x-11fffffe
    at RpcSocket.<anonymous> (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/rpc_socket.js:199:23)
    at Promise.apply (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:788:41)
    at /home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:1391:14
    at runSingle (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:137:13)
    at flush (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Error: Invalid object 0x-11fffffe
    at RpcSocket.<anonymous> (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/rpc_socket.js:199:23)
    at Promise.apply (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:788:41)
    at /home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:1391:14
    at runSingle (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:137:13)
    at flush (/home/travis/build/Stanford-Mobisocial-IoT-Lab/almond-cloud/node_modules/transparent-rpc/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

This does not seem to affect the tests, which pass, and I have never seen it in the real world, but it might be indicative of a race or other timing related bug (maybe related to killing of processes? or maybe related to process ID weirdness in Travis?). We should investigate.

**Comment by gcampax** [comment]
Hopefully fixed by ee0d6064f708d48d6147f016037414ab7f986608
