### ISSUE TITLE
Bug in AlmondApi

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/almond-cloud#119]
Oct 29 16:11:25 thingpedia node[32376]: at <anonymous>
Oct 29 16:11:25 thingpedia node[32376]: at eval (eval at compile (/opt/thingengine/node_modules/thingtalk/lib/jsir.js:541:17), <anonymous>:22:21)
Oct 29 16:11:25 thingpedia node[32376]: at ExecWrapper.invokeAction (/opt/thingengine/node_modules/thingengine-core/lib/apps/exec_wrapper.js:175:36)
Oct 29 16:11:25 thingpedia node[32376]: at Array.map (<anonymous>)
Oct 29 16:11:25 thingpedia node[32376]: at Promise.all.devices.map (/opt/thingengine/node_modules/thingengine-core/lib/apps/exec_wrapper.js:175:63)
Oct 29 16:11:25 thingpedia node[32376]: at MiscellaneousDevice.do_say (/opt/thingengine/node_modules/thingengine-core/lib/devices/builtins/thingengine.builtin.js:60:20)
Oct 29 16:11:25 thingpedia node[32376]: at ExecWrapper.say (/opt/thingengine/node_modules/thingengine-core/lib/apps/exec_wrapper.js:237:29)
Oct 29 16:11:25 thingpedia node[32376]: at ConversationOutput.say (/opt/thingengine/node_modules/thingengine-core/lib/apps/output_queue.js:104:30)
Oct 29 16:11:25 thingpedia node[32376]: at Assistant.notifyAll (/opt/thingengine/almond/assistant.js:52:55)
Oct 29 16:11:25 thingpedia node[32376]: at Array.map (<anonymous>)
Oct 29 16:11:25 thingpedia node[32376]: at Q.all.Object.keys.map (/opt/thingengine/almond/assistant.js:53:44)
Oct 29 16:11:25 thingpedia node[32376]: at AlmondApi.notify (/opt/thingengine/almond/almond_api.js:42:83)
Oct 29 16:11:25 thingpedia node[32376]: Failed to invoke action TypeError: this._formatter.formatForType(...).then is not a function

**Comment by gcampax** [comment]
Fixed by #120
