### ISSUE TITLE
Website service failure

### ISSUE THREAD

**Issue by rayslxu** [Stanford-Mobisocial-IoT-Lab/almond-cloud#14]
```
May 16 18:11:03 thingpedia systemd[1]: thingengine-website@8080.service failed.
May 16 18:11:03 thingpedia systemd[1]: Unit thingengine-website@8080.service entered failed state.
May 16 18:11:03 thingpedia systemd[1]: thingengine-website@8080.service: main process exited, code=exited, status=1/FAILURE
May 16 18:11:03 thingpedia node[24378]: at readableAddChunk (_stream_readable.js:246:13)
May 16 18:11:03 thingpedia node[24378]: at addChunk (_stream_readable.js:263:12)
May 16 18:11:03 thingpedia node[24378]: at Socket.emit (events.js:211:7)
May 16 18:11:03 thingpedia node[24378]: at emitOne (events.js:116:13)
May 16 18:11:03 thingpedia node[24378]: at Socket.JsonDatagramSocket.reader.on (/opt/thingengine/almond/json_datagram_socket.js:48:18)
May 16 18:11:03 thingpedia node[24378]: at JsonDatagramSocket._tryReadMessage (/opt/thingengine/almond/json_datagram_socket.js:88:18)
May 16 18:11:03 thingpedia node[24378]: at JsonDatagramSocket.emit (events.js:211:7)
May 16 18:11:03 thingpedia node[24378]: at emitOne (events.js:116:13)
May 16 18:11:03 thingpedia node[24378]: at RpcSocket._handleMessage (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:294:18)
May 16 18:11:03 thingpedia node[24378]: at RpcSocket._handleReply (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:267:27)
May 16 18:11:03 thingpedia node[24378]: Error: this._delegate.terminate is not a function
May 16 18:11:03 thingpedia node[24378]: ^
May 16 18:11:03 thingpedia node[24378]: throw e;
May 16 18:11:03 thingpedia node[24378]: /opt/thingengine/node_modules/transparent-rpc/node_modules/q/q.js:155
May 16 18:11:03 thingpedia node[7132]: at Pipe.onread (net.js:607:20)
May 16 18:11:03 thingpedia node[7132]: at Socket.Readable.push (_stream_readable.js:208:10)
May 16 18:11:03 thingpedia node[7132]: at readableAddChunk (_stream_readable.js:246:13)
May 16 18:11:03 thingpedia node[7132]: at addChunk (_stream_readable.js:263:12)
May 16 18:11:03 thingpedia node[7132]: at Socket.emit (events.js:211:7)
May 16 18:11:03 thingpedia node[7132]: at emitOne (events.js:116:13)
May 16 18:11:03 thingpedia node[7132]: at Socket.JsonDatagramSocket.reader.on (/opt/thingengine/almond/json_datagram_socket.js:48:18)
May 16 18:11:03 thingpedia node[7132]: at JsonDatagramSocket._tryReadMessage (/opt/thingengine/almond/json_datagram_socket.js:88:18)
May 16 18:11:03 thingpedia node[7132]: at JsonDatagramSocket.emit (events.js:211:7)
May 16 18:11:03 thingpedia node[7132]: at emitOne (events.js:116:13)
May 16 18:11:03 thingpedia node[7132]: at RpcSocket._handleMessage (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:290:18)
May 16 18:11:03 thingpedia node[7132]: at RpcSocket._handleCall (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:221:23)
May 16 18:11:03 thingpedia node[7132]: From previous event:
May 16 18:11:03 thingpedia node[7132]: at process._tickCallback (internal/process/next_tick.js:180:9)
May 16 18:11:03 thingpedia node[7132]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
May 16 18:11:03 thingpedia node[7132]: at RpcSocket.<anonymous> (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:219:29)
May 16 18:11:03 thingpedia node[7132]: at RpcStub.events.EventEmitter.RpcStub.call (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:332:32)
May 16 18:11:03 thingpedia node[7132]: at WebSocketWrapper.onMessage (/opt/thingengine/almond/platform.js:111:14)
May 16 18:11:03 thingpedia node[7132]: at WebSocketWrapper.emit (events.js:211:7)
May 16 18:11:03 thingpedia node[7132]: at emitOne (events.js:116:13)
May 16 18:11:03 thingpedia node[7132]: at WebSocketWrapper.socket.on (/opt/thingengine/node_modules/thingengine-core/lib/tiers/tier_connections.js:246:50)
May 16 18:11:03 thingpedia node[7132]: at WebSocketWrapper.terminate (/opt/thingengine/almond/platform.js:95:24)
May 16 18:11:03 thingpedia node[7132]: TypeError: this._delegate.terminate is not a function
```

**Comment by gcampax** [comment]
The crash is caused by a missing terminate function, yet on that code path the terminate function is implemented and exposed. Needs further investigation.

**Comment by gcampax** [comment]
It looks like the problem has not occurred since, so it was probably something temporary.
