### ISSUE TITLE
Internal server error accessing old gmail page

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/almond-cloud#141]
```
Nov 12 16:48:14 thingpedia1 node[13833]: TypeError: Unexpected type for `value` of Measure
Nov 12 16:48:14 thingpedia1 node[13833]: at Object.value (/opt/thingengine/node_modules/adt/adt.js:464:13)
Nov 12 16:48:14 thingpedia1 node[13833]: at new ctr (/opt/thingengine/node_modules/adt/adt.js:206:35)
Nov 12 16:48:14 thingpedia1 node[13833]: at Function.fromManifest (/opt/thingengine/node_modules/thingtalk/lib/class_def_ast.js:385:44)
Nov 12 16:48:14 thingpedia1 node[13833]: at Object.entries.forEach (/opt/thingengine/node_modules/thingtalk/lib/class_def_ast.js:623:97)
Nov 12 16:48:14 thingpedia1 node[13833]: at Array.forEach (<anonymous>)
Nov 12 16:48:14 thingpedia1 node[13833]: at Function.fromManifest (/opt/thingengine/node_modules/thingtalk/lib/class_def_ast.js:623:42)
Nov 12 16:48:14 thingpedia1 node[13833]: at Object.fromManifest (/opt/thingengine/node_modules/thingtalk/lib/ast_api.js:43:45)
Nov 12 16:48:14 thingpedia1 node[13833]: at Object.migrateManifest (/opt/thingengine/util/import_device.js:405:26)
Nov 12 16:48:14 thingpedia1 node[13833]: at db.withClient (/opt/thingengine/routes/thingpedia_devices.js:78:57)
Nov 12 16:48:14 thingpedia1 node[13833]: at <anonymous>
Nov 12 16:48:14 thingpedia1 node[13833]: From previous event:
Nov 12 16:48:14 thingpedia1 node[13833]: at Object.withClient (/opt/thingengine/util/db.js:94:26)
Nov 12 16:48:14 thingpedia1 node[13833]: at getDetails (/opt/thingengine/routes/thingpedia_devices.js:50:15)
Nov 12 16:48:14 thingpedia1 node[13833]: at router.get (/opt/thingengine/routes/thingpedia_devices.js:113:5)
Nov 12 16:48:14 thingpedia1 node[13833]: at Layer.handle [as handle_request] (/opt/thingengine/node_modules/express/lib/router/layer.js:95:5)
Nov 12 16:48:14 thingpedia1 node[13833]: at next (/opt/thingengine/node_modules/express/lib/router/route.js:137:13)
Nov 12 16:48:14 thingpedia1 node[13833]: at Route.dispatch (/opt/thingengine/node_modules/express/lib/router/route.js:112:3)
Nov 12 16:48:14 thingpedia1 node[13833]: at Layer.handle [as handle_request] (/opt/thingengine/node_modules/express/lib/router/layer.js:95:5)
Nov 12 16:48:14 thingpedia1 node[13833]: at /opt/thingengine/node_modules/express/lib/router/index.js:281:22
Nov 12 16:48:14 thingpedia1 node[13833]: GET /thingpedia/devices/by-id/com.gmail?version=38 500 16.056 ms - 148
```

Link to reproduce: https://almond.stanford.edu/thingpedia/devices/by-id/com.gmail?version=38

(requires admin rights)

**Comment by gcampax** [comment]
Fixed by #162
