### ISSUE TITLE
Crash in Almond API

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/almond-cloud#233]
> Mar 04 14:39:14 thingpedia1 node[3889]: TypeError: Cannot set property 'home' of undefined
Mar 04 14:39:14 thingpedia1 node[3889]: at AlmondApi._slotFill (/opt/thingengine/almond/almond_api.js:334:68)
Mar 04 14:39:14 thingpedia1 node[3889]: at _processPrimitives.then (/opt/thingengine/almond/almond_api.js:366:22)
Mar 04 14:39:14 thingpedia1 node[3889]: at <anonymous>
Mar 04 14:39:14 thingpedia1 node[3889]: at process._tickCallback (internal/process/next_tick.js:189:7)
Mar 04 14:39:14 thingpedia1 node[3889]: From previous event:
Mar 04 14:39:14 thingpedia1 node[3889]: at router.get (/opt/thingengine/routes/my_api.js:92:8)
Mar 04 14:39:14 thingpedia1 node[3889]: at Layer.handle [as handle_request] (/opt/thingengine/node_modules/express/lib/router/layer.js:95:5)
Mar 04 14:39:14 thingpedia1 node[3889]: at next (/opt/thingengine/node_modules/express/lib/router/route.js:137:13)
Mar 04 14:39:14 thingpedia1 node[3889]: at _validate (/opt/thingengine/util/input_validation.js:91:5)
Mar 04 14:39:14 thingpedia1 node[3889]: at /opt/thingengine/util/input_validation.js:97:9
Mar 04 14:39:14 thingpedia1 node[3889]: at Layer.handle [as handle_request] (/opt/thingengine/node_modules/express/lib/router/layer.js:95:5)
Mar 04 14:39:14 thingpedia1 node[3889]: at next (/opt/thingengine/node_modules/express/lib/router/route.js:137:13)
Mar 04 14:39:14 thingpedia1 node[3889]: at /opt/thingengine/util/user.js:219:13

**Comment by gcampax** [comment]
This was fixed by a2ef21caae930a0a39ecf77932ef6654a48bf43d
